### ISSUE TITLE
Choose template engine ?

### ISSUE THREAD

**Issue by dvlppr** [pagekit/pagekit#218]
As Pagekit is symfony2 based, It will be cool to choose between Razr and TWIG.

**Comment by jeff-h** [comment]
If I can add my 2c — I'm comparing various (Symfony-based) CMSs, and the (default) use of Twig is a definite plus from my point of view, as it's a transferable skill that I'm happy to invest in (my bread-and-butter is Drupal, which in 8 is moving to Twig so I will have to learn this for my day job). Learning Razr feels like lock-in to Pagekit, which means I really have to feel a lot more committed to the decision to use Pagekit rather than something that uses Twig.

**Comment by patrickmatsumura** [comment]
As a Symfony dev using Twig, I'd also suggest to at least add Twig as an option. Theme and widget developers should be able to decide what they prefer. Also as @jeff-h mentioned, it does feel like a lock in to page Pagekit.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
