### ISSUE TITLE
marketplace not working

### ISSUE THREAD

**Issue by olanystrom** [pagekit/pagekit#351]
I run pagekit under openlightspeed and I cannot use the marketplace or any other external service.
I get "Cannot connect to the marketplace. Please try again later." when I try.
What modules are used for the external connection for the marketplace?

**Comment by CriseX** [comment]
In case someone else looks at this, they might find this useful.

This was an issue we ended up facing, pagekit uses ajax style requests for all of that stuff once I realized this https was the obvious culprit for us for these and number of similar errors. In theory the origin policies can be used to circumvent this problem as far as I know, however, the official stance on this is that CORS should not be used in this fashion because of potential problems with certificates.

http://www.w3.org/TR/access-control/#user-agent-security

In either case it is something that has to be addressed at the pagekit.com servers that host the API end points.

**Comment by apexlee** [comment]
Could we get an update on this issue? It is a blocker for us as Google have [changed their search algorithm](http://googlewebmastercentral.blogspot.co.uk/2014/08/https-as-ranking-signal.html) to detect whether a site is using the HTTPS protocol.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
