### ISSUE TITLE
Black flashing on pagekit.com

### ISSUE THREAD

**Issue by ApfelUser** [pagekit/pagekit#356]
I am experiencing weird black "flashing" on [Pagekit](http://pagekit.com), [here is a Video](https://www.youtube.com/watch?v=h_0k7QJxAg0)

I am using Chrome Stable 40.0.2214.115 m

**Comment by Mewgood** [comment]
Why create an issue for this? This isn't related to the CMS, and tbh I think this is a problem on your end. Try on another computer if you want.

No "black flashing" problems on Pagekit.com here....

**Comment by ApfelUser** [comment]
Yeah, but I am experiencing this on Linux, OSX and Windows. Only with Chrome, Safari & Opera - so it is and WebKit issue, FF is working fine. I think pagekit would want to fix this because (in my opinion) this is related to the CMS, as the Website presents it.

**Comment by florianletsch** [comment]
Well, the actual reason for this is that the body has a black background. You will see this "flashing" because the page loads and the browser then puts the white and grey elements on top of the background. Depending on your connection speed and browser render time, you might notice this or not. I never noticed until now, but yeah, this could be improved.

However, this is not related to the CMS itself but to the official website's CSS. Thanks for putting this on our list. However, in this context I'll close the issue.

**Comment by ApfelUser** [comment]
@florianletsch Okay, I don't think its a problem with the internet, as I have 236 Mbps download speed right now, I've checked that 10 seconds ago.
