### ISSUE TITLE
Question about current development version...

### ISSUE THREAD

**Issue by CriseX** [pagekit/pagekit#375]
As someone who just found this project, I am already very confused... I see your website refers to razr when it comes to templates, however, the current development version uses a mix of php and markup.

Can someone point me to some direction that would help to explain this  drastic change and what are the plans when it comes to this aspect of the system in the future.

**Comment by florianletsch** [comment]
You are right, the current develop version is very different from last year's alpha release. The project saw some more quite time at the end of last year. When development was picked up again, some design decisions from earlier were questioned and revised (i.e. Razr has been removed). 

The current "develop" status is quickly evolving at the moment but is very close to a new alpha release which will be out in the next couple of weeks.

**Comment by florianletsch** [comment]
And more specificially for the template engine: The develop version currently uses plain PHP templating. The backend has been rewritten completely using [Vue.js](http://vuejs.org/) which is were most of the templates ended up in (vue uses a templating with dom directives and mustache like elements).

Pagekit is equipped to use other templating engines. However, the final decision on which one to add hasn't been answered yet (Twig gained a lot of support from the community, so that one is still on the plate).

**Comment by CriseX** [comment]
Thanks for the clarification on this, I did some searching after posting this as well and read somewhere that having the ability to mix php into templates was at some point something that you were interested in. So I thought that you might end up sticking with mixed templating solution.

Personally I believe that main reason templating engines are a good thing is that they allow themes to be created by non-programmers (although the more modern templating engines resemble programming languages in some sense already) but most of all allow templates to be in theory shared with the knowledge that there is no directly injected php code in them that could be harmful or conflicting and that all the php resulting from templates is generated by the engine following preset rules.

I think there is always going to be wide variety of opinions when it comes to which templating solution is the best. I am partial to Twig myself in this regard. If Pagekit can support multiple templating engines perhaps the best choice to make would be to leave it open ended. In other words make sure you have a stable API on which templating engine extensions can plug into thus allowing each developer make the choice based on their personal preference or the preferences of whoever is designing their templates. If you want a shared repository of themes this might not be the best course of action of course.

Definitely looking forward to what the next iteration of pagekit ends up being like... so far there is a lot to like in the system. These kind of no-nonsense CMS solutions that don't diverge into dozen other areas and end up as trying to be the proverbial kitchen sink are few and far between.

**Comment by inet2800** [comment]
CriseX

In MHO the real issue is if PageKit is viable, or not. YooTheme hyped the project before the Alpha, and then mostly abandoned the project. You observations are spot-on. Those of us that believed the PK initiative simply don't know what to think, or believe at this juncture. On one hand we think that giving YooTheme time and space is the way to go, on the other hand, we have already been mislead more than once. 

If you look at the YooTheme site PK is not even mentioned, not even as a footer link. Make's you think, does it? At then end of the day PK may be nothing more than a marketing gimmick to promote YooTheme. (Really hope that is not the case).

For the time being we continue to watch PK and really hope it comes to live. However, we have begun to take an in depth look at solutions based on Yii2. For example take a look at EasYii, (http://easyiicms.com).

**Comment by saschadube** [comment]
@inet2800 Pagekit is our number one project. You can easily see that by the daily commits we do in the [develop branch](https://github.com/pagekit/pagekit/commits/develop). Nearly 100% of the code base changed in the last 5 months. It took some time to plan the next steps, like adding a [page tree](https://github.com/pagekit/pagekit/issues/157) and using [Vue.js](http://vuejs.org/). Now we a very close to a new Alpha 2 release, which feels more like a major 2.0 release because we revised the whole code base...

We will have a lot to show and talk about in the coming weeks :wink:
