### ISSUE TITLE
[Security] "Remember Me" cookie allows easy password bruteforcing

### ISSUE THREAD

**Issue by eugene-dounar** [pagekit/pagekit#422]
https://github.com/pagekit/pagekit/blob/develop/app/modules/auth/src/RememberMe.php#L191

This should probably use bcrypt/pbkdf2/scrypt so stealing cookies would not allow bruteforcing user's password

**Comment by zanderbaldwin** [comment]
Where have I seen this before? Oh yeah, [now I remember](http://arstechnica.co.uk/security/2015/09/once-seen-as-bulletproof-11-million-ashley-madison-passwords-already-cracked/).

Luckily for the Pagekit developers, what they've done is **absolutely fine**.
The `$password` variable is actually from the user model (`Pagekit\User\Model\User`), meaning that the BCrypt hash stored in the database (in column `pk_system_user.password`) is used rather than the plaintext password.

One way of increasing the security of the Remember Me cookie, if you're interested, is to convert the BCrypt hash to lowercase first (as mentioned in the linked article). Since a BCrypt hash uses both upper and lowercase there will be no way of getting the original hash to check bruteforce attempts against.

Well done for spotting this though (they really should have named it `passwordHash` instead). Too many people in PHP-land overlook the finer details of security, the Ashley Madison leak is a prime example of it.
Keep the mindset you have, as it's better to be wrong about your suspicions than to find out you were right in the future!

**Comment by steffans** [comment]
@zanderbaldwin The arstechnica article is a good read!
