### ISSUE TITLE
Consider Gatekeeper Integration

### ISSUE THREAD

**Issue by paragonie-scott** [pagekit/pagekit#426]
https://github.com/pagekit/pagekit/blob/91d06369914dc4e246f60d9398f8e34c8b9ff6d2/app/modules/auth/src/RememberMe.php#L191

This is not a good model for storing long-term ["remember me"](https://paragonie.com/blog/2015/04/secure-authentication-php-with-long-term-persistence#title.2) authentication tokens. Check out [psecio/gatekeeper](https://github.com/psecio/gatekeeper), which implements the strategy I outlined in the blog post in the previous sentence.

**Comment by zanderbaldwin** [comment]
**N.B.** Thanks for the link to the article, it's brilliant and now saved to my bookmarks! I especially like the [PasswordLock](https://github.com/paragonie/password_lock) library they mentioned.

You're absolutely right, however I don't think implementing an entire authentication & authorisation library like [psecio/gatekeeper](https://github.com/psecio/gatekeeper) is necessary for this, so I thought I would add some context and a solution.

Firstly, [Pagekit](http://pagekit.com) is an impressive project and I can see large adoption in the future. With Pagekit supporting extensions you have no idea who could be using it or how - it's even possible that government (think local council website that links to national government services) could be using it! Security is obviously important for being a reputable open-source project.

### Scenario

Imagine you have an information leak: a full or partial set of the database (which happens to include user data) along with the applications secret key is released. This is more likely than most people think: outsourced developers having read-only access to the database, insecure backups or replication connections, disgruntled employees, the fact that FTP is still a thing, etc.

We're going to assume that the attacker doesn't have access to the server to make modifications, and since the passwords are hashed with BCrypt we (foolishly, though predictably) thought the worst has happened.

### The Problem

```php
sha1($usernameFromLeak . $futureExpiraryDate . $passwordHashFromLeak . $compromisedKey);
```

The attacker now has all the data required for constructing the correct Remember Me cookie value for any user exposed in the information leak, and therefore is able to pose as the user without ever having to enter a password - they even get to choose when they want the cookie to expire.

If you thought confidential data leaking was bad, imagine how catastrophic it would be if an attacker could perform actions as another user? Think:
- Updating address information and making purchases instead of just being able to view order history.
- In the case of the government example above, modifying personal tax information or sending license revocation requests.

A lot of people may think this is all doom and gloom but you'll be amazed at what people build on top of a CMS. Know how much of the internet WordPress powers?

### The Solution

Regardless of whether you hash or encrypt the cookie value, this problem will always occur when using a *constructable value* (ie, always have the same value given a set of predetermined data like username, password hash and secret key) - it has to be sufficiently random.

As the replacement for the Remember Me hash is now random and unable to be generated again, this "token" will have to be persisted into storage and **treated as if it were a plaintext password** (since it holds the same authentication potential): hash that bad boy!

Violà, an attacker cannot construct a Remember Me cookie without brute-forcing a BCrypt hash! In fact, not even the application can predict the value of the Remember Me cookie until the user presents it in a request.

- Consider concatenating the Remember Me token with the users IP and user agent. Makes them a little less portable.

### Performance

- One extra random sequence generation, hash, and database insert on the generation of the cookie.
- Once extra hash comparison on the authentication of a remembered user.

I think that's a fair compromise.

---

Just so you're aware, another solution would be to use [JWT](http://jwt.io/)s to validate that the value of the Remember Me cookie was generated by your application and hasn't been tampered with. This approach however is entirely based on the assumption that the application secret or private key used doesn't get compromised.

Just pointing out that there's more than one way to do something, and there may be a solution out there better than the one I've presented.

**Comment by MalteScharenberg** [comment]
@zanderbaldwin Thanks for your input! We reworked Pagekits session and "remember me" management. 

- No remember me cookie anymore
- 'remember me' information is stored in the session (stored at database)
- Session IDs are hashed
- Auto logout after 15 minutes inactivity
- After a 'remember me' auto login the session id changes

What do you think?

https://github.com/pagekit/pagekit/commit/48a812b2e08747f28b558ac55df98f4ab42ae645
https://github.com/pagekit/pagekit/commit/e66dd047a4511de1113b0b631c27b52a720d028e

**Comment by zanderbaldwin** [comment]
Hi, I'll take a look at the two commits over the weekend - I'm moving today so probably won't have a computer available until Sunday.
