### ISSUE TITLE
Images are not shown when running in localhost

### ISSUE THREAD

**Issue by greenweb73** [pagekit/pagekit#448]
I can not add a image to the article. The message - "Unable to access directory"
Pagekit running in localhost, wamp(OpenServer) in w8, i'm check the permitions, it's all right. admin/system/info - "Writable". How to solve this problem?

**Comment by ste93cry** [comment]
:+1:, I debugged the code and found out that the problem starts in the `getMode` function of the `FinderController` class. The path is expanded to something like C:/htdocs/pagekit/storage/ and the regex in the `mode` function of `FileEvent` class fails because it searches for paths with backslashes.

**Comment by MalteScharenberg** [comment]
Can you please check if this https://github.com/pagekit/pagekit/commit/c362b39230c0bc0308e6849b2a76d8580d5f9e49 commit works on your system?

**Comment by ste93cry** [comment]
It works for me

**Comment by MalteScharenberg** [comment]
@ste93cry Thanks for testing! :+1:

**Comment by greenweb73** [comment]
Thanks for your job, it's cool, it works for me

**Comment by greenweb73** [comment]
Thanks for your job !!! It's cool, it works for me
