### ISSUE TITLE
Duplicated feed widgets which can not be removed 

### ISSUE THREAD

**Issue by ecmel** [pagekit/pagekit#490]
I added a custom rss feed widget, it duplicated itself and now i can not remove any of it.

**Comment by bwhitty** [comment]
I am seeing the same issue. I added an instance of the graph from the Analytics plugin, and of the geolocation heat map from the Analytics plugin and next time I logged in I am seeing the following, with the graph widget (and others) being duplicated multiple times.

![screen shot 2015-11-06 at 12 36 26 pm](https://cloud.githubusercontent.com/assets/1571966/11003862/0e262260-8483-11e5-9c15-94964f7d9591.png)

**Comment by MalteScharenberg** [comment]
You still have this issue with the latest Pagekit release?

**Comment by bwhitty** [comment]
Yes. Just upgrade to 0.10.3 and upgraded the Analytics plugin to 0.10.0. I can't remove the widgets.

When I click the delete button and confirm, and POST hits

`/admin/dashboard/5638247228231`

and the response comes back with 

`{"message":"Widget deleted."}`

But the widget (and all of its duplicates remain.

To alleviate this, could I remove certain rows from the database? Possibly things are just completely out of sync due to botched upgrades in the past.

**Comment by ecmel** [comment]
Still exists in 0.11.2
