### ISSUE TITLE
Chokes on Install

### ISSUE THREAD

**Issue by designer230** [pagekit/pagekit#500]
I've downloaded the latest PageKit as of today Nov 18, 2015. When I get to connect to db on the installer won't go past it. It does create the database but does not populate it. I'm just running it locally on MAMP.

**Comment by adielhercules** [comment]
I had the same problem here, I tryed with both mysql and sqlite drivers. I read about sqlite 3 support on php 5.x and I found that sqlite extension was deprecated now you should use sqlite 3 (installed by default on php 5.x) and so I checked what extensions I had enabled and I had both enabled it was a problem, I disabled the sqlite extension and leaving enabled sqlite 3, tryed to install again and it succeed!

However I think the latest build is having issues, because after installation I still having issues with the cms, specifically this is being showed (with debug mode on):

FatalErrorException in Node.php line 77:
Compile Error: Trait method find has not been applied, because there are collisions with other trait methods on Pagekit\Site\Model\Node

**Comment by koniklos** [comment]
Try to increase max_execution_time in php.ini file. On local xampp installation it was 30 for me, so I've raised it to 120.

On my installation, the loader was spinning, and after a while there was an error on console and php_error_log "PHP Fatal error:  Maximum execution time of 30 seconds exceeded in D:\xampp\htdocs\pagekit\app\vendor\composer\composer\src\Composer\Util\RemoteFilesystem.php on line 333"

Also, the database was partially populated.

**Comment by MalteScharenberg** [comment]
The next Pagekit release (and current dev branch) comes with a reworked installer. 
Please open a new issue if problems occur.
