### ISSUE TITLE
Implement math rendering on blog

### ISSUE THREAD

**Issue by themutt** [pagekit/pagekit#540]
It is useful, especially for scientifical blogs but also for general purpose, to be able to write math when creating or editing a post using markdown. The writer should see a real time rendered math (something like stackedit does).
I don't know whether it is possible do develop it as an extension or it is necessary to review the blog module.

**Comment by florianletsch** [comment]
I think this would be best as an extension. I think it's a great idea for scientific blogs, but not everyone will need this feature. 

Pagekit has a concept of _content plugins_ that are applied to the content when being rendered. I think that would be the right way to implement math rendering as well. Currently, i.e. Markdown is implemented that way: https://github.com/pagekit/pagekit/blob/develop/app/system/modules/content/src/Plugin/MarkdownPlugin.php

We might need to review some of the Blog so that it also applies third party content plugins.
