### ISSUE TITLE
Hero image options won't take effects

### ISSUE THREAD

**Issue by hanlan** [pagekit/pagekit#575]
admin -> site -> pages -> home -> theme -> hero image options

Whether to check any of checkboxes in there (Full viewport height, Invert colors....), none of them is taking effect, checked console, the proper classes are not added in the rendered html.

change to another background image is OK, only those 4 options won't work.

cache disabled and cleaned

**Comment by KevinSupertramp** [comment]
Hi,

Do you have a widget defined for this page on the hero position ?

**Comment by hanlan** [comment]
yes, the widget and hero actually is there, but rendered as by default options, no inverted color, normal height, etc., checked the rendered html code, the proper classes have not been added, like uk-height-viewpoint, uk-text-invert....

**Comment by DarthDestroyer** [comment]
Yep, i can confirm this @	0.11.2

There must be an error somewhere!

I'm not familar with the structure and building mechanism... but, i found some problems.

Nr. 1: set a hero-image => $event['hero_image'] in Theme-index.php is not set / empty!
Nr. 2: select any checkbox you want => $params['classes.navbar'] / $params['classes.sticky'] in Theme-template.php is not set / empty!

It seems, that the ACP Config doenst get to the index, the index isnt reading that values and the default values from the index arent available at template.php...

I found the Problem, because the navbar doenst get the class and stickys.
Then, i tried the Hero Thing and that doesnt work, too!

**Comment by MalteScharenberg** [comment]
Are you using version 0.11.0 of the One-Theme (must be updated separately)?

**Comment by DarthDestroyer** [comment]
Ah... It works ;)

The Source of the Problem was, that the Repo Error blocked the Update Button at the Theme-Settings... There was no Info about an available Update...

With a short look in the gitter chat, i found the answer for that... and then, everything starts working again!

Thank you!

**Comment by hanlan** [comment]
@DarthDestroyer could be where the problem is, thanks, will be keep informed if the problem still there in v1.0
