### ISSUE TITLE
Address bar showing index.php for every page

### ISSUE THREAD

**Issue by DobaKung** [pagekit/pagekit#577]
## Problem

The URL on the address bar is showing `index.php` for every page. For example:

`http://example.com/index.php/about`
`http://example.com/index.php/blog/10`
`http://example.com/index.php/portfolio`

Here is the .htaccess file [htaccess.txt](https://github.com/pagekit/pagekit/files/197609/htaccess.txt). In cPanel, the domain is set to redirect to `http://example.com/$1/index.php/admin` although I set it to disable redirection.

![screen shot 2559-03-31 at 8 03 09 pm](https://cloud.githubusercontent.com/assets/3814520/14176582/f48f617e-f77b-11e5-9c79-9901b3a628bb.png)

## Technical Details

- Pagekit version: 0.10.4
- Webserver: Apache
- Database: MySQL
- PHP Version: 5.6.19

## Troubleshooting

- [/] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [/] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [/] I have tried disabling all installed extensions
- [/] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
You have mod_rewrite enabled?

**Comment by nikaro** [comment]
I also have index.php in every URLs. Is it intended to work this way, or is it a bug ? I have mod_rewrite enabled.

I have managed to strip `index.php` from the URLs by adding this to my VirtualHost configuration :

```
RewriteCond %{THE_REQUEST} ^GET.*index\.php [NC]
RewriteRule /index\.php/(.*) $1 [R=301,NE,L]
```

But it would be nice if links pointed directly to `/` instead of `index.php`.

**Comment by MalteScharenberg** [comment]
It should be the fallback if mod_rewrite is disabled (https://github.com/pagekit/pagekit/blob/develop/app/modules/routing/src/RequestContext.php#L17).

**Comment by nikaro** [comment]
I'm not sure to understand.

You mean that it works like this, as a fallback in the case where mod_rewrite is disabled, and it's not possible to change this ? Or that if mod_rewrite is enabled it should not append, so my Apache configuration is weird ?

As I understand the piece of code you gave me, it looks like the second assertion, but i'm not sure.

Thanks.

**Comment by nikaro** [comment]
Hum my Apache is weird…

```
<IfModule mod_env.c>
    SetEnv HTTP_MOD_REWRITE On
</IfModule>
```

I took this from .htaccess and added it in my VirtualHost configuration and it works now. It's strange that some directives from .htaccess are managed and some others are not :-/

So it's not a problem with Pagekit.

Thanks for this great CMS :-)

**Comment by zhyvytskyi** [comment]
fellows, could you help me with "index.php" ploblem,
i had MOD_REWRITE On

but when I use your code for htaccess, that doesn't help to solve index.php in every URLs

**Comment by tobbexiv** [comment]
Take the default [.htaccess](https://github.com/pagekit/pagekit/blob/develop/.htaccess) and make it possible to use the page with `index.php`. Then check if you can also access the pages after you delete the `index.php` in the url e.g. `YOURSITE/admin/login` instead of `YOURSITE/index.php/admin/login`.
If this is not the case, then something in your general configuration is broken (mod_rewrite disabled or htaccess file not properly configured). You should then first try to fix this issue before investigation further in removing the part from the url.
If you can access the pages without `index.php`, but it is added, then pagekit can somehow not recognize it and adds it automatically. To solve this, you can use my extension which should ensure that all links will be forced to contain no `index.php`: [Enforce Rewrite URL](https://pagekit.com/marketplace/package/tobbe/enforce-modrewrite) Do not use that extension if your pages do not work without the ìndex.php` as otherwise you need to access the database to disable the extension again!

**Comment by zhyvytskyi** [comment]
cool, thanks for your fast answer, now all is fine "default .htaccess" solve my problem.

**Comment by CWhyMedia** [comment]
I have this issue. The rewrite module **is** running, and I have the default .htaccess, yet any page other than the main requires index.php, and if I click on the Main link, I get index.php. I can't access the admin dashboard either, all other pages require the index.php to be present. I'm using the latest Pagekit with Apache 2.4.25 on Raspbian.

**Comment by luizjrdeveloper** [comment]
> **To fix this problem all you need are enable mod_env module on apache**
