### ISSUE TITLE
Error upgrading to 1.0.0

### ISSUE THREAD

**Issue by aptonline** [pagekit/pagekit#585]
## Problem

I'm getting the following error when upgrading to 1.0.0 from 0.11.3

`Warning: include(): stream does not support seeking
`

I've had no issue upgrading from previous builds.

Any ideas?
## Technical Details
- Pagekit version: 0.11.3
- Webserver: Apache
- Database: MySql
- PHP Version: 5.6.17

**Comment by MalteScharenberg** [comment]
I suggest this has to do with the following line of code: https://github.com/pagekit/pagekit/blob/develop/app/installer/src/SelfUpdater.php#L85

Can you verify this (e.g. by removing the lines during update)? 

We are performing this requirements check since 0.11.0. Have you updated from 0.11.* before?

Additionally it would be great if you could provide your php info.

**Comment by MalteScharenberg** [comment]
Please reopen if the issue still persists.
