### ISSUE TITLE
Can't load json file from package.

### ISSUE THREAD

**Issue by N00D13** [pagekit/pagekit#600]
when i upload a new extension or theme i got these error.

```
Can't load json file from package.
```

**Comment by Giusti** [comment]
+1

**Comment by MalteScharenberg** [comment]
Which extension are you trying to upload? The `composer.json` must be located at top-level inside the ZIP.

**Comment by peterbrinck** [comment]
If you download a ZIP from GitHub, you have to extract the file and then rezip it so that the `composer.json` is in the root of the ZIP file, as @MalteScharenberg said

**Comment by MalteScharenberg** [comment]
To be more precise: If you download an automatically generated Github "Zippball" archive, which is generated by clicking on "Download Zip" at the repository overview and at the release page by clicking on "Source code", Github puts all files into a root folder. But anyway these Zibball archive are not ready for installation because some assets or compiled JS sources might be missing.

Maybe we should add distribution zips (like we do for the Pagekit core) for extension releases as well.
In the meantime you can download dist archives at https://pagekit.com/marketplace.

**Comment by N00D13** [comment]
I got these error on the zips from the marketplace!

**Comment by malles** [comment]
@N00D13 
There was an error in the Bixie packages. The latest downloads should be installable.
Easiest way is to install via Marketplace in your Pagekit installation.

**Comment by dlucero23** [comment]
I'm still receiving this error for all four of these packages:
- Analytics Extension by Pagekit
- One Theme by Pagekit
- Hello Theme by Pagekit
- Form Maker by Bixie
