### ISSUE TITLE
Pagekit twig template: attaching 2 css files doesn't work

### ISSUE THREAD

**Issue by midhunps** [pagekit/pagekit#665]
## Problem

I am trying twig templating with pagekit. I am using uikit for the front end styling. I can't find a way to attach 2 css files with the document.
I can success attach one css file and one js file as follows:

                {{ view.style('theme', 'theme:css/uikit/css/uikit.min.css') }}
                {{ view.script('theme', 'theme:css/uikit/js/uikit.min.js', 'jquery') }}

But when i try to attach another css file along with it, only one of them (the second in listed order works):
                {{ view.style('theme', 'theme:css/theme.css') }}
                {{ view.style('theme', 'theme:css/uikit/css/uikit.min.css') }}
                {{ view.script('theme', 'theme:css/uikit/js/uikit.min.js', 'jquery') }}

If I change the order, Which ever css file is mentioned second gets working.

## Technical Details

- Pagekit version: 1.0.3
- Webserver: Apache2 on linux
- Database: MySQL
- PHP Version: 5.5.9-1ubuntu4.16 

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [ ] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by florianletsch** [comment]
This is because the first parameter of the `style()` helper requires a unique identifier for the style. In your example, you call it `theme` in both cases, which is why Pagekit will only take one of the two. Just give them different names, for example:

```
{{ view.style('theme-css', 'theme:css/theme.css') }}
{{ view.style('theme-uikit', 'theme:css/uikit/css/uikit.min.css') }}
```

Note: You might have become confused, because in the original example, the `theme` identifier is used both for the `style()` and for the `script()` helper. This will work, because styles and scripts are managed separately. So internally, you can have a stylesheet of the name `theme` and a script of the name `theme`, but never two stylesheets of the same name.

**Comment by midhunps** [comment]
Thank you florianletsch.. got it.
