### ISSUE TITLE
Escaping of user content

### ISSUE THREAD

**Issue by falko-bgh** [pagekit/pagekit#677]
Hi Pagekit team

Currently all themes (and maybe other PHP templates) just output the unfiltered and unescaped content (like a blog entry title) in the views. This opens a huge gap for possible attacks. Wouldn't it be an option to use TWIG (which escapes all output per default) as template engine instead of PHP?
Pagekit offers some really nice features, but as long as there are such basic leaks I would not use it for any customer project.

**Comment by MalteScharenberg** [comment]
An XSS leak describes the injection of untrusted code in to a trusted context by (usually) somehow bypassing access control. This is not the case for your described scenario. 

Pagekits posts and pages provide HTML support as a feature (like Wordpress, Joomla and many other CMSs), which implies that code injection is always possible for users with write permissions. I won't consider this a problem since write permissions should only be granted to trusted parties (users with write permissions can cause a lot of harm anyway, even besides code injection).

Everything which originates from not trusted sources (e.g. blog comments) gets escaped before displaying.


But I agree that rendering HTML inside the title dose not make much sense. Maybe this should be changed.

**Comment by falko-bgh** [comment]
I agree for fields like the blog content area - but not for stuff like title or maybe fields where nobody needs and uses HTML. 
But wouldn't it make sense to allow only some HTML tags that are harmless? In other words, do you think a `script` tag should be allowed? This is more a general decision, of course, but for me it would be a good option if the allowed tags are at least configurable somewhere in a configuration file.

**Comment by MalteScharenberg** [comment]
`script` dose not make sense in the title, nor is it dangerous, since a user who is allowed to edit the title is allowed to add scripts to the content anyway. I would prefer either full HTML support or none and escape HTML entities instead. Especially `&` is a HTML entity which is probably used often in titles and needs to be escaped to produce valid HTML.
