### ISSUE TITLE
How can we create multi-languages routes

### ISSUE THREAD

**Issue by cdarlens** [pagekit/pagekit#692]
How to create multi-languages routes?

**Comment by florianletsch** [comment]
This is currently not possible, except for manually creating a multi-language menu structure in the site tree. https://github.com/pagekit/pagekit/issues/173

**Comment by q2apro** [comment]
Having no multi-language support makes the CMS unusable for us. We are currently deciding to go away from the long-time player ModX and try some new CMS. Currently our choice would be Bolt and ProcessWire because they have modules that ensure multilingual support. See http://stackoverflow.com/a/38902608/1066234

As soon as there is such a feature implemented in Pagekit, we will consider testing it. Now we do not touch it, since this is one of the most essential features for us.
