### ISSUE TITLE
 ForbiddenException in HttpKernel.php line 104: Insufficient User Rights.

### ISSUE THREAD

**Issue by barkahwibowo** [pagekit/pagekit#717]
## Problem

ForbiddenException in HttpKernel.php line 104: Insufficient User Rights.
## Technical Details
- Pagekit version: 1.0.5
- Webserver: Apache (with Nginx Proxy)
- Database: mariadb/mysql
- PHP Version: 5.6

i got this error in my pagekit installation after updating from 1.0.3 to 1.0.5
new instalation but with content from old installation (imported from old database to new database) also give this error

Whoops, looks like something went wrong.
1/1
ForbiddenException in HttpKernel.php line 104:
Insufficient User Rights.
in HttpKernel.php line 104
at HttpKernel->abort('403', 'Insufficient User Rights.') in index.php line 158
at SiteModule->{closure}(object(RequestEvent), object(Request))
at call_user_func_array(object(Closure), array(object(RequestEvent), object(Request))) in EventDispatcher.php line 123
at EventDispatcher->trigger(object(RequestEvent), array(object(Request))) in HttpKernel.php line 72
at HttpKernel->handle(object(Request)) in Application.php line 67
at Application->run() in app.php line 24
at require_once('/home/username/domain.com/app/system/app.php') in index.php line 40

**Comment by MalteScharenberg** [comment]
At which page and did you update the Blog as well?

**Comment by barkahwibowo** [comment]
default pagekit homepage
i'm not using blog

**Comment by MalteScharenberg** [comment]
Can you send me a link to your page with user credentials? You can contact me via Gitter privat messages.

**Comment by j94305** [comment]
I have noticed similar behaviour. When I access a URL /doesnotexist that does not exist, the content of app/system/modules/theme/views/error.php seems to be displayed. I can change that to do a redirection to an error page /error. Fine. That takes care of 404. However, if I get "unauthorized" exceptions (403), this does not seem to work anymore. The "Whoops..." message is displayed (with exception detail if debug mode is enabled). It seems to me there is either a registration for some exceptions missing in the application, or there is an error while the error is displayed, and that's why my error page does not appear.

It would be nice to have a tab "Exceptions" in the admin interface to simply list handler pages for the different exceptions. How's that for PageKit 1.0.9? :-)

**Comment by j94305** [comment]
Ok. After fiddling a bit with this labyrinth of directories and files, I found something that works.

In /app/system/modules/site/index.php, I write now

```
        'request' => [function() use ($app) {
            if (!$app['node']->hasAccess($app['user'])) {
                // $app['kernel']->abort(403, __('Insufficient User Rights.'));
                $app['view']->render('system/unauthorized.php');
            }
        }, -100],
```

and create a file /app/system/modules/theme/views/unauthorized.php with this content:

```
<?php
header("Location: /login");
exit(0);
?>
```

And now this happens:

- If a non-existing page is tried to retrieve: error.php is used
- If an existing page is tried to retrieve but access rights are insufficient: unauthorized.php is used.

I have no idea if this is the canonical way of handling it but it seems to achieve the desired effect :-)

Cheers!

**Comment by MalteScharenberg** [comment]
@barkahwibowo Please reopen if the issue still exists.
@j94305 You could create a feature request for this. :)
