### ISSUE TITLE
Authentication in Maintanence Mode

### ISSUE THREAD

**Issue by LrMiLoef** [pagekit/pagekit#733]
## Problem

When the maintanence mode is enabled and nobody is logged in, the modal for "session expired" will be shown. this overlays the login-page from the admin area.

![unbenannt](https://cloud.githubusercontent.com/assets/14238642/17726169/81fc688a-6451-11e6-8a72-46f0d5493222.PNG)

## Technical Details

- Pagekit version: 1.0.7
- Webserver: Apache/2.4.20
- Database: MySQL
- PHP Version: 7.0.6

**Comment by MalteScharenberg** [comment]
I think this is caused by the translation API route which is blocked falsely by the maintenance listener. Currently API routes are only accessible in maintenance mode by administrators or uses with  maintenance privileges. 

The latest Pagekit update introduced this new feature of authenticating requests blocked because of maintenance mode  (https://github.com/pagekit/pagekit/issues/727). So prior to this update just wrong translations where shown. Now this bug is more present :) 

We have to find a way to allow some routes to be requested unauthenticated in maintenance mode.
