### ISSUE TITLE
Data passed from controller to view is changed

### ISSUE THREAD

**Issue by xorinzor** [pagekit/pagekit#742]
## Problem

when you'd do the following in a controller:
```
return [
                '$view' => [
                    'title' => 'Home',
                    'name' => 'myextension:view/index.php'
                ],
                'custom' => '<img src="%icon%" />'
            ];
```

and `<?= $custom; ?>` in the View, the result will end up looking like `<img src="/%icon%" />`.

@malles found that this is most likely because of the \Pagekit\View\Event\ResponseListener

## Technical Details

- Pagekit version: 1.0.8
- Webserver: apache
- Database: mysql
- PHP Version: 5.6.24

**Comment by florianletsch** [comment]
Yes, you are right. However, this has nothing to do with the data passed from controller to the view. Instead, the rendered view is changed before it is sent back to the browser.

As you point out correctly, this is performed by the `ResponseListener`. Its task is to detect relative URLs in elements such as images, links etc and rewrite them depending on the location of your Pagekit installation. If you are interested, see the complete regular expression that matches these elements: https://github.com/pagekit/pagekit/blob/develop/app/system/modules/view/src/Event/ResponseListener.php#L10

This feature allows for a few things, for example having the file display both in the markdown editor and the rendered frontend. Also, links don't break when moving the Pagekit installation, because the files are not linked with absolute references.

However, in your case, a rendered output like `<img src="%icon%" />` will also be picked up by the `ResponseListener`. That's no surprise, because `%icon%` could potentially be a weird, but possible relative link on your site (just like `home`, `#footer` or `hello/mister/feynman`, but not `/lol` because that one starts with a leading slash).

To conclude, this is actually expected behavior. 

_Now, what can you do to fix your issue?_

I am assuming that you are using %icon% as a placeholder for some frontend replacement? Is it possible for you to make this placeholder look like an absolute link, so that it doesn't get rewritten? For example use something like `/icon/` oder `/%icon%/`. There might be other solutions available, but this is the first solution I can think of.

**Comment by xorinzor** [comment]
but shouldn't it just leave the `%icon%` alone if it has nothing to replace it with, instead of prepending a `/` to it?

I fixed it by changing it into `#icon#` but thats just a workaround

**Comment by florianletsch** [comment]
> but shouldn't it just leave the %icon% alone if it has nothing to replace it with, instead of prepending a / to it?

No, it is not trying to _replace_ anything. It is merely detecting relative URLs and rewriting them to be an absolute URL while taking into account the locating of your Pagekit installation.

An example to clear this up: 

Your content links to a file called `storage/apollo11.jpg` as follows: `<img src="storage/apollo11.jpg" alt="">`. Also the Pagekit installation is located at `https://domain.com/pagekit/`. 

You can already see a problem that the URL  `storage/apollo11.jpg` has to be changed in certain situations: When editing in the backend, the URL is `https://domain.com/pagekit/admin`, so simply leaving the relative URL would try to link to `https://domain.com/pagekit/admin/storage/apollo11.jpg` which doesn't exist. 

The same is true when you display the post on certain urls, for example on a blog post where the URL would be `https://domain.com/pagekit/blog/hello-world`.  

Pagekit solves this with the `ResponseListener`. Every URL that looks like a relative URL is rewritten. `<img src="storage/apollo11.jpg" alt="">` becomes `<img src="/pagekit/storage/apollo11.jpg" alt="">`. Here the `/pagekit/` part is added because that is the current path to the Pagekit installation. In your specific case, Pagekit is installed on the root, which is why only a simple `/` is added.

I currently have no better solution for you than choosing a placeholder that does not look like a relative URL. As you've found out yourself, `#icon#` will work. Other possibilities would be `/icon/` or `/%icon%/`.
