### ISSUE TITLE
Using pagekit in a subfolder instead of root

### ISSUE THREAD

**Issue by LordOfSpoon** [pagekit/pagekit#767]
I have page kit installed in a subfolder (example.com/blog). I only want to use pagekit as a blog so my problems is that when I go to a post, the url is normal but under a subfolder looks off (example.com/blog/index.php/blog/postslughere). I need it to be (example.com/blog/postslughere) just like it would be if it was installed on the root directory.

Any ideas?

**Comment by pyatnitsev** [comment]
What web server do you use?

It's looks like webserver need to be configured for working with pagekit. I use config files from this page: http://silex.sensiolabs.org/doc/master/web_servers.html

**Comment by vishnu1991** [comment]
I am having same problem as @LordOfSpoon .
I am having my pagekit setup at `https://domain.com/blog/`

Now the **problem** is when i open any post then the url looks like
`https://domain.com/blog/blog/my-post-title`  (Note:the blog is repeated twice!)
Instead of  `https://domain.com/blog/my-post-title`

**Comment by MalteScharenberg** [comment]
Please use Gitter or the Pagekit forum for support requests.
