### ISSUE TITLE
Error session handling on my CentOS VM

### ISSUE THREAD

**Issue by MartianGreed** [pagekit/pagekit#799]
Hey, 

i've got this weird issue popping up when i try to install pagekit on my VM

Warning: SessionHandler::read(): Session data file is not created by your uid

I've already tried to fix permissions as it was said by users using Symfony3!

Can you guys help?

- Pagekit version: latest
- Webserver: Apache 2.4
- Database: Mariadb 5.5
- PHP Version: 7.0.15

**Comment by Alex237** [comment]
Hey, same forme,
I am using a Vagrant box :
"debian/jessie64" With Debian GNU/Linux 8.7 (jessie)

- Pagekit version: latest
- Webserver: nginx version: nginx/1.6.2
- Database: MySQL (mysql  Ver 14.14 Distrib 5.5.54)
- PHP PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21)

**Comment by Alex237** [comment]
Fixed, Inspired By this @MartianGreed :
 [https://github.com/pagekit/pagekit/issues/618#issuecomment-214967850](https://github.com/pagekit/pagekit/issues/618#issuecomment-214967850)
 for nginx edit file `/etc/nginx/nginx.conf` and change `user www-data;` to `user vagrant;`
then, in 

` /etc/php5/fpm/pool.d/www.conf`

change 

`listen.owner = www-data`
`listen.group = www-data`

to

`listen.owner = vagrant`
`listen.group = vagrant`

**Comment by Alex237** [comment]
Fixed with this for me, https://github.com/fourkitchens/dev2-playbooks/issues/99
[https://github.com/fourkitchens/dev2-playbooks/issues/99#issue-50234289](https://github.com/fourkitchens/dev2-playbooks/issues/99#issue-50234289)

[https://gist.github.com/falexandrou/8965063](https://gist.github.com/falexandrou/8965063)
[https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#virtualbox](https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#virtualbox)

I have also change synced_folder to :
`
config.vm.synced_folder "./pagekit", "/var/www/html" , group: "www-data", owner: "www-data"
  `

**Comment by MalteScharenberg** [comment]
@Alex237 If I understand you right this issue is related to virtualbox or is there anything we can do to improve Pagekit? 
@MartianGreed Did it work for you as well?

**Comment by Alex237** [comment]
@MalteScharenberg yes, it is related to virtualbox, only if you are using vagrant with config.vm.synced_folder to share local folder with the virtual machine.
