### ISSUE TITLE
Pagekit development dead?

### ISSUE THREAD

**Issue by Akselselsing** [pagekit/pagekit#807]
Hi, I've noticed that Pagekit hasn't been updated in a while. Has the team behind stopped supporting Pagekit?

**Comment by SPQRInc** [comment]
They are currently working on Uikit 3 and YooTheme Pro. I guess we have to be patient.

**Comment by suemcnab** [comment]
I can be patient, but I would like to hear what future plans are ;-)

**Comment by saschadube** [comment]
As @SPQRInc said, we are working on [UIkit 3](https://getuikit.com) and on [YOOtheme Pro](http://yootheme.com/pro/). Both will come to Pagekit once they are ready.

**Comment by angay9** [comment]
@saschadube Is pagekit still alive?

**Comment by Fosphatic** [comment]
Well pagekit is alive, but yootheme has no love leftover for pagekit unfortinately. It would be just helpful if they would even try to make the life for developers who wanted to write code for it or did, but no merging policy isn't helpful at all. So the most developers left supporting this project. That is very very sad as it is a very nice cms that just need at least a maintanance release for all the depencies and not left in the dark as it is since ages now.

**Comment by absoluto** [comment]
well, BY NOW it´s dead!

**Comment by farhanianz** [comment]
I guess, its dead now..
