### ISSUE TITLE
Store XSS in post title and context 

### ISSUE THREAD

**Issue by Xyntax** [pagekit/pagekit#814]
- Pagekit version: 1.0.11
- Webserver: Apache
- Database: MySQL
- PHP Version: 7

Login user who has "Manage own posts" privilege can inject arbitrary web script or HTML via post editor, XSS vulnerability will be triggered by visiting `/blog` or `/blog/{post_id}`.

PoC
---
![pic](http://static.cdxy.me/Screenshot%20from%202017-04-05%2014-31-26.png)
![pic](http://static.cdxy.me/Screenshot%20from%202017-04-05%2014-33-55.png)

**Comment by MalteScharenberg** [comment]
An XSS leak describes the injection of untrusted code in to a trusted context by (usually) somehow bypassing access control. This is not the case for your described scenario.

Pagekits posts and pages provide HTML support as a feature (like Wordpress, Joomla and many other CMSs), which implies that code injection is always possible for users with write permissions. I won't consider this a problem since write permissions should only be granted to trusted parties (users with write permissions can cause a lot of harm anyway, even besides code injection).

For potential further security issues please send a mail to info@pagekit.com, so that we are able to evaluate and patch the vulnerability before it is disclosed to the public.

**Comment by Jayin** [comment]
👍
