### ISSUE TITLE
DOM XSS in editor.js

### ISSUE THREAD

**Issue by Xyntax** [pagekit/pagekit#815]
DOM XSS was found in editor form (editor.js)
  
Triggers while copying content (contains XSS payloads) somewhere into editor, or just edit context posted by other user. 

PoC
---
![pic](http://static.cdxy.me/Screenshot%20from%202017-04-05%2014-59-56.png)

- Pagekit version: 1.0.11
- Webserver: Apache
- Database: MySQL
- PHP Version: 7

**Comment by MalteScharenberg** [comment]
An XSS leak describes the injection of untrusted code in to a trusted context by (usually) somehow bypassing access control. This is not the case for your described scenario.

Pagekits posts and pages provide HTML support as a feature (like Wordpress, Joomla and many other CMSs), which implies that code injection is always possible for users with write permissions. I won't consider this a problem since write permissions should only be granted to trusted parties (users with write permissions can cause a lot of harm anyway, even besides code injection).

For potential further security issues please send a mail to info@pagekit.com, so that we are able to evaluate and patch the vulnerability before it is disclosed to the public.
