### ISSUE TITLE
unabled to access directory

### ISSUE THREAD

**Issue by alex1504** [pagekit/pagekit#825]
At the backend , when I run into site-setting column and I want to upload a logo img, it just show me a tip 'unabled to access directory' and the upload form doesn't occurs, how can I solve this problem?

**Comment by tobbexiv** [comment]
To me it looks that the scripts are not allowed to mdify the storage on the server due to insufficient rigths for the user which is used for access. What is the info status? Path to information: /admin/system/info and then select "Permissions"? If there are not all folders listed as writable, then there are missing rights for the user on the server. In this case you must adjust the rights for your user on the server manually.

**Comment by MalteScharenberg** [comment]
Please use Gitter or the Pagekit forum for support requests.
