### ISSUE TITLE
Suggestion: Remove UI-kit boilerplate

### ISSUE THREAD

**Issue by jvlaar** [pagekit/pagekit#830]
## Suggestion

Currently the default page and blog views contain a lot of UI-kit bloat in the form of classes. While UI-kit can be a great tool for developing layouts not everyone wants to use it. Either to minimize filesizes/requests or simply because of personal preference.

My suggestion is to remove the UI-kit boilerplate from the Pagekit core and instead move it the One and/or Hello theme.

## Technical Details

- Pagekit version: 1.0.11

**Comment by florianletsch** [comment]
We had a discussion about that in the beginning. However, here is our reasoning why we left the classes: We needed _some_ way to style the system views. So we needed to add some classes. Our options were to use generic class names like "navigation", "comment", etc. This is also how other CMS do it (look at the amount of classes any wordpress theme needs to include for example).

However, UIkit already provides styling for all these cases that we needed to style. We therefore used the class names already present in UIkit. So instead of using a class "comment", we named it "uk-comment". These names are just generic labels, so we kept the "uk-" prefix out of convenience for all themes that want to use UIkit.

Note that this does not mean that a theme needs to include UIkit! You can instead style the classes used by the system views. You find these classes in the Hello theme. Just add your own CSS to these classes. https://github.com/pagekit/theme-hello/blob/master/css/theme.css
