### ISSUE TITLE
Module name change prevents execution of update scripts.

### ISSUE THREAD

**Issue by tobbexiv** [pagekit/pagekit#886]
In case of a name change of a module, the update will work like an install instead of an update. The update functions are not executed and thus possible changes to the database are lost. This is due to a check whether a module with this name already exists (which is not the case if the module name is changed). Thus, a module name change might prevent the execution of important updates for an extension.

See [my analysis in the forum](https://pagekit-forum.org/forum/thread/267-migrating-extension-s-config/?postID=1288#post1288) for more information.

A valid scenario for a module name change would be the introduction of a namespace.

**Comment by MalteScharenberg** [comment]
I think changing a modules name is a non standard case and should be handled by a custom script in the installation hook. Do you see any downsides by solving this inside the installation hook?

**Comment by SPQRInc** [comment]
Hm - when I look at the marketplace, there are a lot of extensions that do not have a "namespaced" extension name. In some cases that's not critical, but some names could easily conflict with other extensions that don't have an unique name, too ("Gallery", "Blog", ...).

So I think it's important to convince the devs to switch over to an unique name (=> "namespaced").

Considering this, I think it would be "expected behavior" to change the name during the update-process.  Just my opinion ;)
