### ISSUE TITLE
Portfolio: "Projects per page" Not working

### ISSUE THREAD

**Issue by nodefive** [pagekit/pagekit#932]
I've have several projects in Bixie Portfolio. I've set 10 per page, but it shows all in one page, and it makes the page heavy and slow to load.

Anyone can confirm? Can be fixed? Chrome shows no ajax js or any other error. The console is clean.

**Comment by humantex** [comment]
Changing that setting only affects the number shown per page in the admin's list on the back end, and is not a pagination control setting for the public portfolio page. The only way to trim the public side in the number shown, is to use the 'tags' functionality to enable some filtering. Example... https://for-sale.lumiworx.com/for-sale

I'm presume this was by design - assuming that there wouldn't be a massive number of projects you'd want to show, but perhaps 8, 10, 12 of the most important or most recent ones.

**Comment by nodefive** [comment]
Thank you humantex!! Well the assumption is wrong. I have two portfolios (added an extra one for another section) and both have a considerable number of items, and they are growing.

I've compress and optimized all the teaser images, but after 50 or so the page starts to lag during the loading. I'll probably won't go for this approach you showed me because that lumiworx's page is loading in full, probably won't solve the "heaviness" problem. I don't want to sort them, but to make the page shorter so it loads faster and without visual "glitch" while it does.  I'll have to tweak the code to implement this into the plugin. 

Thanks again mate!
